package tryCatch;

public class ThrowException {

	public static void main(String[] args) {
		// 의도적으로 exception을 발생시키는 것.
		// 테스트할 때 사용할 수 있음.
		throw new RuntimeException();
	}

}
